export const ROOT_COUNTER = "ROOT_COUNTER";
export const SACRAL_COUNTER = "SACRAL_COUNTER";
export const SOLARPLEXUS_COUNTER = "SOLARPLEXUS_COUNTER";
export const HEART_COUNTER = "HEART_COUNTER";
export const THROAT_COUNTER = "THROAT_COUNTER";
export const THIRDEYE_COUNTER = "THIRDEYE_COUNTER";
export const CROWN_COUNTER = "CROWN_COUNTER";
